name: Artifact Jar Storing Nexus Repository
on:
  push:
    branches: [ "main" ]

jobs:
  pre_build:
    name: pre-compile-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile & Test
        run: |
          mvn compile
          mvn test

  build:
    name: Deploy to Nexus
    runs-on: ubuntu-latest
    needs: pre_build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: nexus
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Deploy artifact
        run: mvn deploy


